/// JSON parsing helpers used by all model files in `lib/models`.
///
/// These functions provide defensive, null-safe coercion of loosely-typed
/// JSON values (as produced by `dart:convert`) into the strongly-typed
/// fields used by the ported model classes. They mirror the behaviour of
/// the native UnilivePro JSON helpers and the code generated by
/// `json_serializable`, but are hand-written so the project does not need
/// a build_runner step.
///
/// Every helper accepts a `dynamic` value and never throws - invalid or
/// missing values fall back to a sensible default.
library;

/// Parses a [String] from [v].
///
/// Returns [defaultValue] when [v] is `null`. Non-string values are
/// coerced via `toString()`.
String? parseString(dynamic v, [String? defaultValue]) {
  if (v is String) return v;
  if (v is Map) {
    final id = v['_id'] ?? v['id'];
    if (id != null) return id.toString();
  }
  if (v == null) return defaultValue;
  return v.toString();
}

/// Parses an [int] from [v].
///
/// Accepts [int], [double], numeric [String]s and [bool] (true -> 1).
/// Falls back to [defaultValue] (default `0`) for anything else.
int parseInt(dynamic v, [int defaultValue = 0]) {
  if (v is int) return v;
  if (v is double) return v.toInt();
  if (v is num) return v.toInt();
  if (v is String) {
    final parsed = int.tryParse(v);
    if (parsed != null) return parsed;
    final d = double.tryParse(v);
    if (d != null) return d.toInt();
    return defaultValue;
  }
  if (v is bool) return v ? 1 : 0;
  return defaultValue;
}

/// Parses a nullable [int] from [v].
///
/// Like [parseInt] but returns `null` instead of a default when the value
/// cannot be interpreted as an integer.
int? parseIntOrNull(dynamic v) {
  if (v is int) return v;
  if (v is double) return v.toInt();
  if (v is num) return v.toInt();
  if (v is String) {
    final parsed = int.tryParse(v);
    if (parsed != null) return parsed;
    final d = double.tryParse(v);
    if (d != null) return d.toInt();
    return null;
  }
  if (v is bool) return v ? 1 : 0;
  return null;
}

/// Parses a [bool] from [v].
///
/// Accepts native [bool], numbers (non-zero -> true) and the strings
/// "true"/"false" (case-insensitive) as well as "1"/"0".
/// Falls back to [defaultValue] (default `false`) otherwise.
bool parseBool(dynamic v, [bool defaultValue = false]) {
  if (v is bool) return v;
  if (v is num) return v != 0;
  if (v is String) {
    switch (v.toLowerCase()) {
      case 'true':
      case '1':
      case 'yes':
        return true;
      case 'false':
      case '0':
      case 'no':
        return false;
    }
  }
  return defaultValue;
}

/// Parses a [double] from [v].
///
/// Accepts [double], [int], numeric [String]s and [bool].
/// Falls back to [defaultValue] (default `0`) otherwise.
double parseDouble(dynamic v, [double defaultValue = 0]) {
  if (v is double) return v;
  if (v is int) return v.toDouble();
  if (v is num) return v.toDouble();
  if (v is String) {
    final parsed = double.tryParse(v);
    if (parsed != null) return parsed;
    final i = int.tryParse(v);
    if (i != null) return i.toDouble();
    return defaultValue;
  }
  if (v is bool) return v ? 1.0 : 0.0;
  return defaultValue;
}

/// Parses a [num] from [v].
///
/// Accepts [num], numeric [String]s and [bool]. Falls back to
/// [defaultValue] (default `0`) otherwise. Prefer this over [parseInt] /
/// [parseDouble] for fields whose JSON type may legitimately be either
/// integer or floating point (e.g. coin balances).
num parseNum(dynamic v, [num defaultValue = 0]) {
  if (v is num) return v;
  if (v is String) {
    final parsed = num.tryParse(v);
    if (parsed != null) return parsed;
    return defaultValue;
  }
  if (v is bool) return v ? 1 : 0;
  return defaultValue;
}

/// Parses a [List<String>] from [v].
///
/// Accepts a [List] of strings/objects. If an element is a [Map] with an
/// `image` or `url` key, that value is used; otherwise the element is
/// coerced to a non-empty string. Returns an empty list for null/non-list.
List<String> parseStringList(dynamic v) {
  if (v is! List) return const [];
  final result = <String>[];
  for (final e in v) {
    if (e is String) {
      if (e.isNotEmpty) result.add(e);
    } else if (e is Map) {
      final url = e['image']?.toString() ?? e['url']?.toString() ?? e['badge']?.toString();
      if (url?.isNotEmpty == true) result.add(url!);
    } else if (e != null) {
      final s = e.toString();
      if (s.isNotEmpty) result.add(s);
    }
  }
  return result;
}

/// Parses a [List] of model objects from [v] using [fromJson].
///
/// Each element of [v] must be a `Map`; elements that are not maps are
/// skipped. Returns an empty list when [v] is `null` or not a list.
List<T> parseList<T>(
  dynamic v,
  T Function(Map<String, dynamic>) fromJson,
) {
  if (v is List) {
    final result = <T>[];
    for (final element in v) {
      if (element is Map<String, dynamic>) {
        result.add(fromJson(element));
      } else if (element is Map) {
        result.add(fromJson(Map<String, dynamic>.from(element)));
      }
    }
    return result;
  }
  return <T>[];
}
